package SillasFast;

import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author pace_
 */
public class SillasFast extends javax.swing.JFrame {
    //Atributo
    private TablaHash almacen;
    /**
     * Creates new form SillasFast
     */
    public SillasFast() {
        initComponents();
        this.setLocationRelativeTo(null);
        almacen = new TablaHash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        PanelPrincipal = new javax.swing.JPanel();
        PanelDefault = new javax.swing.JPanel();
        PanelBuscar = new javax.swing.JPanel();
        botonBuscar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextAreaID = new javax.swing.JTextField();
        panelEncontrado = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        infoLabelTipo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        infoLabelMarca = new javax.swing.JLabel();
        infoLabelMaterial = new javax.swing.JLabel();
        infoLabelResistencia = new javax.swing.JLabel();
        infoLabelOpinion = new javax.swing.JLabel();
        PanelNuevo = new javax.swing.JPanel();
        BtnCancelar = new javax.swing.JButton();
        BtnAgregar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        ComboBoxMarca = new javax.swing.JComboBox<>();
        ComboBoxMaterial = new javax.swing.JComboBox<>();
        ComboBoxResistencia = new javax.swing.JComboBox<>();
        TextFileOpinion = new javax.swing.JTextField();
        MenuPrincipal = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        menuArchivoImportar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuNuevo = new javax.swing.JMenu();
        nuevo = new javax.swing.JMenuItem();
        MenuBuscar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        PanelPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout PanelDefaultLayout = new javax.swing.GroupLayout(PanelDefault);
        PanelDefault.setLayout(PanelDefaultLayout);
        PanelDefaultLayout.setHorizontalGroup(
            PanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );
        PanelDefaultLayout.setVerticalGroup(
            PanelDefaultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        PanelPrincipal.add(PanelDefault, "card4");

        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel5.setText("Buscar");

        jLabel8.setText("Ingrese el ID:");

        TextAreaID.addKeyListener(new KeyAdapter() {   //numero es el nombre del TextField
            public void keyTyped(KeyEvent e) {         //sólo cambialo por el que tienes
                char c = e.getKeyChar();
                if (!(Character.isDigit(c) ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_DELETE))) {
                getToolkit().beep();
                e.consume();
            }
        }
    });
    TextAreaID.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TextAreaIDActionPerformed(evt);
        }
    });

    jLabel9.setText("Tipo");

    infoLabelTipo.setText("----------------------------------------");

    jLabel11.setText("Marca");

    jLabel12.setText("Material");

    jLabel13.setText("Resistencia");

    jLabel14.setText("Opinion");

    infoLabelMarca.setText("----------------------------------------");

    infoLabelMaterial.setText("----------------------------------------");

    infoLabelResistencia.setText("----------------------------------------");

    infoLabelOpinion.setText("----------------------------------------");

    javax.swing.GroupLayout panelEncontradoLayout = new javax.swing.GroupLayout(panelEncontrado);
    panelEncontrado.setLayout(panelEncontradoLayout);
    panelEncontradoLayout.setHorizontalGroup(
        panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelEncontradoLayout.createSequentialGroup()
            .addGap(67, 67, 67)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(infoLabelTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addComponent(infoLabelMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabelMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabelResistencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(infoLabelOpinion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap(74, Short.MAX_VALUE))
    );
    panelEncontradoLayout.setVerticalGroup(
        panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(panelEncontradoLayout.createSequentialGroup()
            .addGap(33, 33, 33)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(infoLabelTipo))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel11)
                .addComponent(infoLabelMarca))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel12)
                .addComponent(infoLabelMaterial))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel13)
                .addComponent(infoLabelResistencia))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelEncontradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelEncontradoLayout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addGap(0, 0, Short.MAX_VALUE))
                .addComponent(infoLabelOpinion, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
            .addContainerGap())
    );

    javax.swing.GroupLayout PanelBuscarLayout = new javax.swing.GroupLayout(PanelBuscar);
    PanelBuscar.setLayout(PanelBuscarLayout);
    PanelBuscarLayout.setHorizontalGroup(
        PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PanelBuscarLayout.createSequentialGroup()
            .addGap(78, 78, 78)
            .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelBuscarLayout.createSequentialGroup()
                    .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 204, Short.MAX_VALUE)
                    .addComponent(botonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(71, 71, 71))
                .addGroup(PanelBuscarLayout.createSequentialGroup()
                    .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBuscarLayout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TextAreaID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))
    );
    PanelBuscarLayout.setVerticalGroup(
        PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBuscarLayout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jLabel5)
            .addGap(51, 51, 51)
            .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel8)
                .addComponent(TextAreaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(222, 222, 222)
            .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botonSalir)
                .addComponent(botonBuscar))
            .addGap(58, 58, 58))
        .addGroup(PanelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBuscarLayout.createSequentialGroup()
                .addGap(0, 104, Short.MAX_VALUE)
                .addComponent(panelEncontrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 104, Short.MAX_VALUE)))
    );

    PanelPrincipal.add(PanelBuscar, "card2");

    BtnCancelar.setText("Cancelar");
    BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnCancelarActionPerformed(evt);
        }
    });

    BtnAgregar.setText("Agregar");
    BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnAgregarActionPerformed(evt);
        }
    });

    jLabel7.setText("Agregar Sillas");

    jLabel1.setText("Tipo");

    jLabel2.setText("Marca");

    jLabel3.setText("Material");

    jLabel4.setText("Resistencia");

    jLabel6.setText("Opinion");

    ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Académica", "Moderna", "Gamer", "Oficina", "Infantiles", "Sillon" }));
    ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ComboBoxTipoActionPerformed(evt);
        }
    });

    ComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Amazon", "Fatake", "Office", "Ahorrera", "Gaming" }));

    ComboBoxMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Madera", "Poliester", "Platico Crudo", "Metal", "Algodon" }));

    ComboBoxResistencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Mucha", "Normal", "Poca" }));

    TextFileOpinion.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            TextFileOpinionActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout PanelNuevoLayout = new javax.swing.GroupLayout(PanelNuevo);
    PanelNuevo.setLayout(PanelNuevoLayout);
    PanelNuevoLayout.setHorizontalGroup(
        PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PanelNuevoLayout.createSequentialGroup()
            .addGap(54, 54, 54)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelNuevoLayout.createSequentialGroup()
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(150, 150, 150)
                    .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelNuevoLayout.createSequentialGroup()
                        .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxMarca, 0, 141, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelNuevoLayout.createSequentialGroup()
                        .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFileOpinion)
                            .addComponent(ComboBoxResistencia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxMaterial, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addContainerGap(136, Short.MAX_VALUE))
    );
    PanelNuevoLayout.setVerticalGroup(
        PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelNuevoLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel7)
            .addGap(40, 40, 40)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1)
                .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(ComboBoxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(7, 7, 7)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(ComboBoxMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(ComboBoxResistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(TextFileOpinion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
            .addGroup(PanelNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(BtnCancelar)
                .addComponent(BtnAgregar))
            .addGap(18, 18, 18))
    );

    PanelPrincipal.add(PanelNuevo, "card3");

    MenuArchivo.setText("Archivo");

    menuArchivoImportar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    menuArchivoImportar.setText("Importar");
    MenuArchivo.add(menuArchivoImportar);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Exportar");
    MenuArchivo.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Guardar");
    MenuArchivo.add(jMenuItem3);

    MenuPrincipal.add(MenuArchivo);

    MenuNuevo.setText("Nuevo");
    MenuNuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            MenuNuevoActionPerformed(evt);
        }
    });

    nuevo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    nuevo.setText("Nuevo");
    nuevo.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            nuevoActionPerformed(evt);
        }
    });
    MenuNuevo.add(nuevo);

    MenuPrincipal.add(MenuNuevo);

    MenuBuscar.setText("Buscar");

    jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem1.setText("Buscar");
    jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem1ActionPerformed(evt);
        }
    });
    MenuBuscar.add(jMenuItem1);

    MenuPrincipal.add(MenuBuscar);

    setJMenuBar(MenuPrincipal);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGap(18, 18, 18))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(18, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelDefault);
        PanelPrincipal.repaint();
        PanelPrincipal.revalidate();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void MenuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuNuevoActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelNuevo);
        PanelPrincipal.repaint();
        PanelPrincipal.revalidate();
    }//GEN-LAST:event_nuevoActionPerformed

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        String campoTipo, campoMaterial, campoMarca, campoResistencia, campoOpinion;
        if(ComboBoxTipo.getSelectedIndex() == 0 
                || ComboBoxMaterial.getSelectedIndex() == 0
                || ComboBoxMarca.getSelectedIndex() == 0
                || ComboBoxResistencia.getSelectedIndex() == 0
                || TextFileOpinion.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Hay campos vacíos", "ERROR 69", JOptionPane.ERROR_MESSAGE);
        }else{
            campoTipo = (String) ComboBoxTipo.getSelectedItem();
            campoMaterial =(String) ComboBoxMaterial.getSelectedItem();
            campoMarca = (String) ComboBoxMarca.getSelectedItem();
            campoResistencia = (String) ComboBoxResistencia.getSelectedItem();
            campoOpinion = TextFileOpinion.getText();
            //Crear Objeto Silla
            Silla nuevo = new Silla(campoTipo,campoMaterial,campoResistencia,campoMarca,campoOpinion);
            almacen.insertar(nuevo);
            String mensaje = "Silla nueva\n ID: " + nuevo.getID() + " ";
            JOptionPane.showMessageDialog(null, mensaje, "Agregado!!! n.n", JOptionPane.INFORMATION_MESSAGE);
            //
            PanelPrincipal.removeAll();
            PanelPrincipal.add(PanelDefault);
            PanelPrincipal.repaint();
            PanelPrincipal.revalidate();
        }
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void TextFileOpinionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFileOpinionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFileOpinionActionPerformed

    private void TextAreaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextAreaIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextAreaIDActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelDefault);
        PanelPrincipal.repaint();
        PanelPrincipal.revalidate();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PanelPrincipal.removeAll();
        PanelPrincipal.add(PanelBuscar);
        PanelPrincipal.repaint();
        PanelPrincipal.revalidate();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        int campoID;
        Silla encontrado;
        if(TextAreaID.getText().length() == 0)
            JOptionPane.showMessageDialog(null, "No ha Igresado un ID", "ERROR 69", JOptionPane.ERROR_MESSAGE);
        else{
            campoID = Integer.parseInt(TextAreaID.getText());
            encontrado = almacen.buscar(campoID);
            if(encontrado == null){
                infoLabelTipo.setText("No se encontró Silla con el ID: "+campoID);
                infoLabelMarca.setText("No se encontró Silla con el ID: "+campoID);
                infoLabelMaterial.setText("No se encontró Silla con el ID: "+campoID);
                infoLabelResistencia.setText("No se encontró Silla con el ID: "+campoID);
                infoLabelOpinion.setText("No se encontró Silla con el ID: "+campoID);
            }else{
                infoLabelTipo.setText(encontrado.getTipo());
                infoLabelMarca.setText(encontrado.getMarca());
                infoLabelMaterial.setText(encontrado.getMaterial());
                infoLabelResistencia.setText(encontrado.getResistencia());
                infoLabelOpinion.setText(encontrado.getOpinion());
            }
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SillasFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SillasFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SillasFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SillasFast.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SillasFast().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JComboBox<String> ComboBoxMarca;
    private javax.swing.JComboBox<String> ComboBoxMaterial;
    private javax.swing.JComboBox<String> ComboBoxResistencia;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenu MenuBuscar;
    private javax.swing.JMenu MenuNuevo;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JPanel PanelBuscar;
    private javax.swing.JPanel PanelDefault;
    private javax.swing.JPanel PanelNuevo;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JTextField TextAreaID;
    private javax.swing.JTextField TextFileOpinion;
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel infoLabelMarca;
    private javax.swing.JLabel infoLabelMaterial;
    private javax.swing.JLabel infoLabelOpinion;
    private javax.swing.JLabel infoLabelResistencia;
    private javax.swing.JLabel infoLabelTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem menuArchivoImportar;
    private javax.swing.JMenuItem nuevo;
    private javax.swing.JPanel panelEncontrado;
    // End of variables declaration//GEN-END:variables
}
